<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="firefighter">
    <!-- MATERIALS    -->
    <xacro:macro name="color" params="name rgba">
        <material name="${name}">
            <color rgba="${rgba}" />
        </material>
    </xacro:macro>
    <!-- correct colors   -->
    <xacro:color name="aluminium" rgba="1 0 0 1"/>
    <xacro:color name="blue" rgba="0 0 1 1"/>
    <xacro:color name="black" rgba="1 0 0 1"/>
    <!--    COMMON DEFINITION-->
    <xacro:macro name="expandable" params="name">
        <link name="${name}">
            <xacro:macro name="expandable_geometry">
                <geometry>
                    <cylinder length="0.2" radius="0.02"/>
                </geometry>
                <origin xyz="0 0 ${-0.2/2}"/>
            </xacro:macro>
            <visual>
                <xacro:expandable_geometry/>
                <material name="aluminium"/>
            </visual>
            <collision>
                <xacro:expandable_geometry/>
            </collision>
            <intertial>
                <mass value="0.2"/>
            </intertial>
        </link>
    </xacro:macro>

    <xacro:macro name="pipe" params="name length radius=0.02 spin=-1">
        <link name="${name}">
            <xacro:macro name="pipe_geometry">
                <geometry>
                    <cylinder length="${length}" radius="${radius}"/>
                </geometry>
                <origin xyz="0 0 ${spin*length/2}"/>
            </xacro:macro>
            <visual>
                <xacro:pipe_geometry/>
                <material name="aluminium"/>
            </visual>
            <collision>
                <xacro:pipe_geometry/>
            </collision>
             <intertial>
                <mass value="${0.1*length}"/>
            </intertial>
        </link>
    </xacro:macro>

    <xacro:macro name="wheel" params="name">
        <link name="${name}">
            <xacro:macro name="wheel_geometry">
                <geometry>
                    <cylinder length="0.05" radius="0.05"/>
                </geometry>
            </xacro:macro>
            <visual>
                <xacro:wheel_geometry/>
                <material name="black"/>
            </visual>
            <collision>
                <xacro:wheel_geometry/>
            </collision>
             <intertial>
                <mass value="0.2"/>
            </intertial>
        </link>
    </xacro:macro>

    <!-- The base of the robot. All other parts including legs and extendable upper body is attached to the base.
       Base contains the battery and the main computer and is the haviest part of the robot. -->
    <link name="base_link">
        <xacro:macro name="base_link_geometry">
            <geometry>
                <box size="0.3 0.4 0.4"></box>
            </geometry>
        </xacro:macro>
        <visual>
            <xacro:base_link_geometry/>
            <material name="blue"/>
        </visual>
        <collision>
            <xacro:base_link_geometry/>
        </collision>
         <intertial>
            <mass value="15"/>
        </intertial>
    </link>

    <!-- expandable for upper body    -->
    <xacro:expandable name="expandable_from_base_link_to_upper_body"/>
    <joint name="base_link_to_expandable_to_upper_body" type="fixed">
        <parent link="base_link"/>
        <child link="expandable_from_base_link_to_upper_body"/>
        <origin xyz="0 0 0.4 "/>
    </joint>

    <!-- upper body    -->
    <link name="upper_body_link">
        <xacro:macro name="upper_body_geometry">
            <geometry>
                <box size="0.3 0.4 0.2"></box>
            </geometry>
        </xacro:macro>
        <visual>
            <xacro:upper_body_geometry/>
            <material name="blue"/>
        </visual>
        <collision>
            <xacro:upper_body_geometry/>
        </collision>
         <intertial>
            <mass value="4"/>
        </intertial>
    </link>
    <joint name="expandable_from_base_link_to_upper_body_to_upper_body" type="prismatic">
         <axis xyz="0 0 1"/>
         <limit effort="1000.0" lower="-0.1" upper="1.2" velocity="0.5"/>
        <parent link="expandable_from_base_link_to_upper_body"/>
        <child link="upper_body_link"/>
        <origin xyz="0 0 0.1"/>
    </joint>

    <!-- legs    -->
    <xacro:macro name="leg" params="position parent x_shift z_shift">
        <!-- hip       -->
        <xacro:pipe name="${position}_leg_hip" length="0.3"/>
        <joint name="${parent}_to_${position}_leg_hip" type="revolute">
            <axis xyz="1 0 0"/>
            <limit effort="1000.0" lower="-1.5708" upper="1.5708" velocity="0.5"/>
            <parent link="${parent}"/>
            <child link="${position}_leg_hip"/>
            <origin xyz="${x_shift} 0 ${z_shift}"/>
        </joint>

        <!-- ankle        -->
        <xacro:pipe name="${position}_leg_ankle" length="0.3"/>
        <joint name="${position}_leg_hip_to_${position}_leg_ankle" type="revolute">
            <axis xyz="1 0 0"/>
            <limit effort="1000.0" lower="-1.5708" upper="1.5708" velocity="0.5"/>
            <parent link="${position}_leg_hip"/>
            <child link="${position}_leg_ankle"/>
            <origin xyz="0 0 -0.31"/>
        </joint>

        <!-- foot heel-->
        <link name="${position}_foot_heel">
            <xacro:macro name="foot_heel_geometry">
                <geometry>
                    <box size="0.1 0.3 0.1"></box>
                </geometry>
                <origin xyz="0 0 -0.05"/>
            </xacro:macro>
            <visual>
                <xacro:foot_heel_geometry/>
                <material name="blue"/>
            </visual>
            <collision>
                <xacro:foot_heel_geometry/>
            </collision>
             <intertial>
                <mass value="0.5"/>
            </intertial>
        </link>
        <joint name="${position}_leg_ankle_to_${position}_foot_heel" type="fixed">
            <parent link="${position}_leg_ankle"/>
            <child link="${position}_foot_heel"/>
            <origin xyz="0 0.1 -0.31"/>
        </joint>
        <xacro:expandable name="${position}_foot_extendable"/>
        <joint name="${position}_foot_heel_to_${position}_foot_extendable" type="fixed">
            <parent link="${position}_foot_heel"/>
            <child link="${position}_foot_extendable"/>
            <origin xyz="0 -0.35 -0.05" rpy="1.5708 0 0"/>
        </joint>
        <!-- foot ball-->
        <link name="${position}_foot_ball">
            <xacro:macro name="foot_ball_geometry">
                <geometry>
                    <box size="0.1 0.2 0.1"></box>
                </geometry>
                <origin xyz="0 0 0.05"/>
            </xacro:macro>
            <visual>
                <xacro:foot_ball_geometry/>
                <material name="blue"/>
            </visual>
            <collision>
                <xacro:foot_ball_geometry/>
            </collision>
             <intertial>
                <mass value="0.5"/>
            </intertial>
        </link>
        <joint name="${position}_foot_extendable_to_${position}_foot_ball" type="prismatic">
            <axis xyz="0 1 0"/>
            <limit effort="1000.0" lower="-0.1" upper="0.5" velocity="0.5"/>
            <parent link="${position}_foot_extendable"/>
            <child link="${position}_foot_ball"/>
            <!--  move rpy to the actual part instead of the joint           -->
            <origin xyz="0 0.05 0.1" rpy="1.5708 0 0"/>
        </joint>
        <!-- rear wheel        -->
        <xacro:wheel name="${position}_rear_wheel"/>
        <joint name="${position}_foot_heel_to_${position}_rear_wheel" type="fixed">
            <parent link="${position}_foot_heel"/>
            <child link="${position}_rear_wheel"/>
            <!--  move rpy to the actual part instead of the joint           -->
            <origin xyz="0 0 -0.1" rpy="0 1.5708 0"/>
        </joint>

        <!-- front wheel        -->
        <xacro:wheel name="${position}_front_wheel"/>
        <joint name="${position}_foot_ball_to_${position}_front_wheel" type="fixed">
            <parent link="${position}_foot_ball"/>
            <child link="${position}_front_wheel"/>
            <!--  move rpy to the actual part instead of the joint           -->
            <origin xyz="0 0 0.1" rpy="0 1.5708 0"/>
        </joint>
    </xacro:macro>
    <xacro:leg position="left" parent="base_link" x_shift="0.09" z_shift="-0.2"/>
    <xacro:leg position="right" parent="base_link" x_shift="-0.09" z_shift="-0.2"/>

    <!-- arms    -->
    <xacro:macro name="arm" params="position parent x_shift spin pitch=0">
        <!-- shoulder        -->
        <xacro:pipe name="${position}_arm_shoulder_x" length="0.01" spin="1"/>
        <joint name="${parent}_to_${position}_arm_shoulder_x" type="revolute">
            <axis xyz="1 0 0"/>
            <limit effort="1000.0" lower="-1.5708" upper="1.5708" velocity="0.5"/>
            <parent link="${parent}"/>
            <child link="${position}_arm_shoulder_x"/>
            <origin xyz="${x_shift} 0 0" rpy="1.5708 ${pitch} ${spin*1.5708}"/>
        </joint>
        <xacro:pipe name="${position}_arm_shoulder_y" length="0.3" spin="1"/>
        <joint name="${position}_arm_shoulder_x_to_${position}_arm_shoulder_y" type="revolute">
            <axis xyz="0 1 0"/>
            <limit effort="1000.0" lower="-1.5708" upper="1.5708" velocity="0.5"/>
            <parent link="${position}_arm_shoulder_x"/>
            <child link="${position}_arm_shoulder_y"/>
            <origin xyz="0 0 0.02"/>
        </joint>

        <!-- writs        -->
        <xacro:pipe name="${position}_arm_wrist_x" length="0.01" spin="1"/>
        <joint name="${position}_arm_shoulder_y_to_${position}_arm_wrist_x" type="revolute">
            <axis xyz="1 0 0"/>
            <limit effort="1000.0" lower="-1.5708" upper="1.5708" velocity="0.5"/>
            <parent link="${position}_arm_shoulder_y"/>
            <child link="${position}_arm_wrist_x"/>
            <origin xyz="0 0 0.31"/>
        </joint>
        <xacro:pipe name="${position}_arm_wrist_y" length="0.3" spin="1"/>
        <joint name="${position}_arm_wrist_x_to_${position}_arm_wrist_y" type="revolute">
            <axis xyz="0 1 0"/>
            <limit effort="1000.0" lower="-1.5708" upper="1.5708" velocity="0.5"/>
            <parent link="${position}_arm_wrist_x"/>
            <child link="${position}_arm_wrist_y"/>
            <origin xyz="0 0 0.02"/>
        </joint>

        <!-- palms        -->
        <xacro:pipe name="${position}_arm_palm" length="0.05" spin="1"/>
        <joint name="${position}_arm_wrist_y_to_${position}_arm_palm" type="fixed">
            <parent link="${position}_arm_wrist_y"/>
            <child link="${position}_arm_palm"/>
            <origin xyz="0 0 0.31"/>
        </joint>

        <!-- gripper        -->
        <xacro:macro name="gripper" params="arm_position gripper_position parent yaw=0">
            <!-- top knuckle           -->
            <xacro:pipe name="${arm_position}_arm_${gripper_position}_gripper_top_knuckle" length="0.05" radius="0.005" spin="1"/>
           <joint name="${parent}_${arm_position}_arm_${gripper_position}_gripper_top_knuckle" type="revolute">
                <axis xyz="0 1 0"/>
                <limit effort="1000.0" lower="0" upper="1.5708" velocity="0.5"/>
                <parent link="${parent}"/>
                <child link="${arm_position}_arm_${gripper_position}_gripper_top_knuckle"/>
                <origin xyz="0 0 0.05" rpy="0 0.523599 ${yaw}"/>
            </joint>

            <!-- bottom knuckle           -->
            <xacro:pipe name="${arm_position}_arm_${gripper_position}_gripper_middle_knuckle" length="0.05" radius="0.005" spin="1"/>
           <joint name="${arm_position}_arm_${gripper_position}_gripper_top_knuckle_to_${arm_position}_arm_${gripper_position}_gripper_middle_knuckle" type="fixed">
                <parent link="${arm_position}_arm_${gripper_position}_gripper_top_knuckle"/>
                <child link="${arm_position}_arm_${gripper_position}_gripper_middle_knuckle"/>
                <origin xyz="0 0 0.05" rpy="0 -1.047201225112 0"/>
            </joint>
        </xacro:macro>
        <xacro:gripper parent="${position}_arm_palm" arm_position="${position}" gripper_position="left"  />
        <xacro:gripper parent="${position}_arm_palm" arm_position="${position}" gripper_position="right" yaw="3.14159"/>
        <xacro:gripper parent="${position}_arm_palm" arm_position="${position}" gripper_position="bottom" yaw="-1.5708"/>
    </xacro:macro>
    <xacro:arm position="left" parent="upper_body_link" x_shift="0.17" spin="1"/>
    <xacro:arm position="right" parent="upper_body_link" x_shift="-0.17" spin="-1" pitch="3.14159"/>

    <!-- camera box   -->
    <link name="camera_box">
         <xacro:macro name="camera_box_geometry">
            <geometry>
                <box size="0.1 0.1 0.1"></box>
            </geometry>
             <origin xyz="0 -0.05 0.05"/>
        </xacro:macro>
        <visual>
            <xacro:camera_box_geometry/>
            <material name="blue"/>
        </visual>
        <collision>
            <xacro:camera_box_geometry/>
        </collision>
         <intertial>
            <mass value="1"/>
        </intertial>
    </link>
    <joint name="upper_body_link_to_camera_box" type="continuous">
        <axis xyz="0 0 1"/>
        <parent link="upper_body_link"/>
        <child link="camera_box"/>
        <origin xyz="0 -0.1 0.1"/>
    </joint>
</robot>